// Auto-generated seed data for marketplace
import productBike from "@/assets/product-bike.jpg";
import productBooks from "@/assets/product-books.jpg";
import productLaptop from "@/assets/product-laptop.jpg";
import productLamp from "@/assets/product-lamp.jpg";
import student1 from "@/assets/student-1.jpg";
import student2 from "@/assets/student-2.jpg";
import student3 from "@/assets/student-3.jpg";
import type { MarketplaceListing } from "./marketplace";

export const seedListingsGenerated: MarketplaceListing[] = [
  {
    id: "item-gen-1",
    sellerId: "seller-karan",
    sellerName: "Karan",
    sellerAvatar: student2,
    sellerCourse: "1st year Civil",
    sellerRating: 4.5,
    title: "MacBook Air M2",
    description: "Barely used MacBook Air M2, 8GB RAM, 256GB SSD. Under warranty.",
    category: "Electronics" as any,
    condition: "Good" as any,
    price: 77800,
    pickupArea: "Gate 2",
    images: [productLaptop],
    status: "sold",
    tags: ["macbook","air","m2"],
    createdAt: "2026-07-11T16:11:45.331Z",
    views: 281,
    saves: 25,
    offerCount: 0,
  },
  {
    id: "item-gen-2",
    sellerId: "seller-priya",
    sellerName: "Priya",
    sellerAvatar: student3,
    sellerCourse: "2nd year ECE",
    sellerRating: 4.7,
    title: "Dell XPS 13",
    description: "Great for coding, i7 10th gen, 16GB RAM. Small scratch on lid.",
    category: "Electronics" as any,
    condition: "Fair" as any,
    price: 57900,
    pickupArea: "Hostel 3",
    images: [productLaptop],
    status: "active",
    tags: ["dell","xps","13"],
    createdAt: "2026-07-02T04:11:45.332Z",
    views: 290,
    saves: 14,
    offerCount: 3,
  },
  {
    id: "item-gen-3",
    sellerId: "seller-sneha",
    sellerName: "Sneha",
    sellerAvatar: student1,
    sellerCourse: "2nd year IT",
    sellerRating: 4.7,
    title: "ThinkPad T14",
    description: "Solid build, 16GB RAM, perfect for heavy programming.",
    category: "Electronics" as any,
    condition: "Used" as any,
    price: 40650,
    pickupArea: "Hostel 4",
    images: [productLaptop],
    status: "active",
    tags: ["thinkpad","t14"],
    createdAt: "2026-07-10T14:11:45.332Z",
    views: 188,
    saves: 16,
    offerCount: 3,
  },
  {
    id: "item-gen-4",
    sellerId: "seller-aisha",
    sellerName: "Aisha",
    sellerAvatar: student3,
    sellerCourse: "1st year ECE",
    sellerRating: 4.8,
    title: "ThinkPad T14",
    description: "Solid build, 16GB RAM, perfect for heavy programming.",
    category: "Electronics" as any,
    condition: "New" as any,
    price: 35500,
    pickupArea: "Gate 2",
    images: [productLaptop],
    status: "active",
    tags: ["thinkpad","t14"],
    createdAt: "2026-06-13T13:11:45.332Z",
    views: 362,
    saves: 61,
    offerCount: 1,
  },
  {
    id: "item-gen-5",
    sellerId: "seller-priya",
    sellerName: "Priya",
    sellerAvatar: student3,
    sellerCourse: "2nd year ECE",
    sellerRating: 4.7,
    title: "iPad Pro 11\"",
    description: "With Apple Pencil 2. Used for taking notes.",
    category: "Electronics" as any,
    condition: "New" as any,
    price: 52650,
    pickupArea: "ECE Block",
    images: [productLaptop],
    status: "sold",
    tags: ["ipad","pro","11\""],
    createdAt: "2026-07-14T10:11:45.333Z",
    views: 66,
    saves: 6,
    offerCount: 1,
  },
  {
    id: "item-gen-6",
    sellerId: "seller-rohan",
    sellerName: "Rohan",
    sellerAvatar: student2,
    sellerCourse: "2nd year Mech",
    sellerRating: 4.6,
    title: "iPad Pro 11\"",
    description: "With Apple Pencil 2. Used for taking notes.",
    category: "Electronics" as any,
    condition: "Used" as any,
    price: 48450,
    pickupArea: "Sports Complex",
    images: [productLaptop],
    status: "active",
    tags: ["ipad","pro","11\""],
    createdAt: "2026-07-12T06:11:45.333Z",
    views: 125,
    saves: 25,
    offerCount: 0,
  },
  {
    id: "item-gen-7",
    sellerId: "seller-priya",
    sellerName: "Priya",
    sellerAvatar: student3,
    sellerCourse: "2nd year ECE",
    sellerRating: 4.7,
    title: "Samsung Galaxy Tab S8",
    description: "Includes S-Pen. Good for media and notes.",
    category: "Electronics" as any,
    condition: "Good" as any,
    price: 42550,
    pickupArea: "Main Gate",
    images: [productLaptop],
    status: "active",
    tags: ["samsung","galaxy","tab"],
    createdAt: "2026-06-17T16:11:45.333Z",
    views: 288,
    saves: 51,
    offerCount: 8,
  },
  {
    id: "item-gen-8",
    sellerId: "seller-karan",
    sellerName: "Karan",
    sellerAvatar: student2,
    sellerCourse: "1st year Civil",
    sellerRating: 4.5,
    title: "Logitech G502 Gaming Mouse",
    description: "Perfect working condition. RGB works.",
    category: "Electronics" as any,
    condition: "New" as any,
    price: 2400,
    pickupArea: "Canteen Area",
    images: [productLaptop],
    status: "active",
    tags: ["logitech","g502","gaming"],
    createdAt: "2026-07-11T21:11:45.333Z",
    views: 305,
    saves: 57,
    offerCount: 14,
  },
  {
    id: "item-gen-9",
    sellerId: "seller-arjun",
    sellerName: "Arjun",
    sellerAvatar: student2,
    sellerCourse: "3rd year EEE",
    sellerRating: 4.8,
    title: "Logitech G502 Gaming Mouse",
    description: "Perfect working condition. RGB works.",
    category: "Electronics" as any,
    condition: "Like new" as any,
    price: 2100,
    pickupArea: "Gate 2",
    images: [productLaptop],
    status: "active",
    tags: ["logitech","g502","gaming"],
    createdAt: "2026-07-13T16:11:45.333Z",
    views: 5,
    saves: 0,
    offerCount: 0,
  },
  {
    id: "item-gen-10",
    sellerId: "seller-maya",
    sellerName: "Maya",
    sellerAvatar: student1,
    sellerCourse: "Final year IT",
    sellerRating: 4.9,
    title: "Logitech G502 Gaming Mouse",
    description: "Perfect working condition. RGB works.",
    category: "Electronics" as any,
    condition: "Good" as any,
    price: 2150,
    pickupArea: "Gate 2",
    images: [productLaptop],
    status: "active",
    tags: ["logitech","g502","gaming"],
    createdAt: "2026-06-26T00:11:45.333Z",
    views: 49,
    saves: 4,
    offerCount: 1,
  },
  {
    id: "item-gen-11",
    sellerId: "seller-nisha",
    sellerName: "Nisha",
    sellerAvatar: student3,
    sellerCourse: "Final year CSE",
    sellerRating: 4.9,
    title: "Keychron K2 Mechanical Keyboard",
    description: "Brown switches, wireless. Clean.",
    category: "Electronics" as any,
    condition: "Used" as any,
    price: 5650,
    pickupArea: "Hostel 5",
    images: [productLaptop],
    status: "active",
    tags: ["keychron","k2","mechanical"],
    createdAt: "2026-06-20T01:11:45.333Z",
    views: 122,
    saves: 13,
    offerCount: 1,
  },
  {
    id: "item-gen-12",
    sellerId: "seller-rahul",
    sellerName: "Rahul",
    sellerAvatar: student2,
    sellerCourse: "4th year Mech",
    sellerRating: 4.6,
    title: "Keychron K2 Mechanical Keyboard",
    description: "Brown switches, wireless. Clean.",
    category: "Electronics" as any,
    condition: "New" as any,
    price: 5800,
    pickupArea: "Hostel 4",
    images: [productLaptop],
    status: "sold",
    tags: ["keychron","k2","mechanical"],
    createdAt: "2026-06-25T15:11:45.333Z",
    views: 185,
    saves: 37,
    offerCount: 8,
  },
  {
    id: "item-gen-13",
    sellerId: "seller-nisha",
    sellerName: "Nisha",
    sellerAvatar: student3,
    sellerCourse: "Final year CSE",
    sellerRating: 4.9,
    title: "LG 24\" IPS Monitor",
    description: "1080p 75Hz. No dead pixels.",
    category: "Electronics" as any,
    condition: "New" as any,
    price: 6350,
    pickupArea: "Canteen Area",
    images: [productLaptop],
    status: "active",
    tags: ["lg","24\"","ips"],
    createdAt: "2026-07-11T08:11:45.333Z",
    views: 23,
    saves: 1,
    offerCount: 0,
  },
  {
    id: "item-gen-14",
    sellerId: "seller-priya",
    sellerName: "Priya",
    sellerAvatar: student3,
    sellerCourse: "2nd year ECE",
    sellerRating: 4.7,
    title: "LG 24\" IPS Monitor",
    description: "1080p 75Hz. No dead pixels.",
    category: "Electronics" as any,
    condition: "Used" as any,
    price: 5100,
    pickupArea: "Girls Hostel Block A",
    images: [productLaptop],
    status: "active",
    tags: ["lg","24\"","ips"],
    createdAt: "2026-07-03T01:11:45.333Z",
    views: 271,
    saves: 51,
    offerCount: 8,
  },
  {
    id: "item-gen-15",
    sellerId: "seller-maya",
    sellerName: "Maya",
    sellerAvatar: student1,
    sellerCourse: "Final year IT",
    sellerRating: 4.9,
    title: "Sony WH-1000XM4 Headphones",
    description: "Noise cancellation is top notch. Pads are good.",
    category: "Electronics" as any,
    condition: "Good" as any,
    price: 16800,
    pickupArea: "Gate 2",
    images: [productLaptop],
    status: "sold",
    tags: ["sony","wh-1000xm4","headphones"],
    createdAt: "2026-07-01T14:11:45.333Z",
    views: 385,
    saves: 30,
    offerCount: 4,
  },
  {
    id: "item-gen-16",
    sellerId: "seller-jordan",
    sellerName: "Jordan",
    sellerAvatar: student2,
    sellerCourse: "3rd year CSE",
    sellerRating: 4.8,
    title: "Sony WH-1000XM4 Headphones",
    description: "Noise cancellation is top notch. Pads are good.",
    category: "Electronics" as any,
    condition: "Used" as any,
    price: 17750,
    pickupArea: "Hostel 5",
    images: [productLaptop],
    status: "active",
    tags: ["sony","wh-1000xm4","headphones"],
    createdAt: "2026-06-24T23:11:45.333Z",
    views: 90,
    saves: 10,
    offerCount: 0,
  },
  {
    id: "item-gen-17",
    sellerId: "seller-rahul",
    sellerName: "Rahul",
    sellerAvatar: student2,
    sellerCourse: "4th year Mech",
    sellerRating: 4.6,
    title: "Casio fx-991EX Calculator",
    description: "Allowed in exams. Works perfectly.",
    category: "Electronics" as any,
    condition: "Used" as any,
    price: 950,
    pickupArea: "Sports Complex",
    images: [productLaptop],
    status: "active",
    tags: ["casio","fx-991ex","calculator"],
    createdAt: "2026-06-26T16:11:45.333Z",
    views: 138,
    saves: 13,
    offerCount: 0,
  },
  {
    id: "item-gen-18",
    sellerId: "seller-karan",
    sellerName: "Karan",
    sellerAvatar: student2,
    sellerCourse: "1st year Civil",
    sellerRating: 4.5,
    title: "Casio fx-991EX Calculator",
    description: "Allowed in exams. Works perfectly.",
    category: "Electronics" as any,
    condition: "Like new" as any,
    price: 850,
    pickupArea: "Sports Complex",
    images: [productLaptop],
    status: "sold",
    tags: ["casio","fx-991ex","calculator"],
    createdAt: "2026-07-06T10:11:45.333Z",
    views: 132,
    saves: 26,
    offerCount: 3,
  },
  {
    id: "item-gen-19",
    sellerId: "seller-nisha",
    sellerName: "Nisha",
    sellerAvatar: student3,
    sellerCourse: "Final year CSE",
    sellerRating: 4.9,
    title: "Anker 20000mAh Power Bank",
    description: "Charges phone 4 times.",
    category: "Electronics" as any,
    condition: "Fair" as any,
    price: 1600,
    pickupArea: "Hostel 5",
    images: [productLaptop],
    status: "active",
    tags: ["anker","20000mah","power"],
    createdAt: "2026-07-12T10:11:45.333Z",
    views: 114,
    saves: 6,
    offerCount: 1,
  },
  {
    id: "item-gen-20",
    sellerId: "seller-sneha",
    sellerName: "Sneha",
    sellerAvatar: student1,
    sellerCourse: "2nd year IT",
    sellerRating: 4.7,
    title: "Database System Concepts (Silberschatz)",
    description: "Standard textbook for DBMS. Highlighted.",
    category: "Books" as any,
    condition: "Like new" as any,
    price: 400,
    pickupArea: "Hostel 1",
    images: [productBooks],
    status: "active",
    tags: ["database","system","concepts"],
    createdAt: "2026-06-25T04:11:45.333Z",
    views: 387,
    saves: 23,
    offerCount: 1,
  },
  {
    id: "item-gen-21",
    sellerId: "seller-sneha",
    sellerName: "Sneha",
    sellerAvatar: student1,
    sellerCourse: "2nd year IT",
    sellerRating: 4.7,
    title: "Database System Concepts (Silberschatz)",
    description: "Standard textbook for DBMS. Highlighted.",
    category: "Books" as any,
    condition: "Like new" as any,
    price: 550,
    pickupArea: "Hostel 4",
    images: [productBooks],
    status: "active",
    tags: ["database","system","concepts"],
    createdAt: "2026-07-07T09:11:45.333Z",
    views: 38,
    saves: 4,
    offerCount: 0,
  },
  {
    id: "item-gen-22",
    sellerId: "seller-aisha",
    sellerName: "Aisha",
    sellerAvatar: student3,
    sellerCourse: "1st year ECE",
    sellerRating: 4.8,
    title: "Operating System Concepts (Galvin)",
    description: "Good condition, no missing pages.",
    category: "Books" as any,
    condition: "Used" as any,
    price: 450,
    pickupArea: "Hostel 3",
    images: [productBooks],
    status: "active",
    tags: ["operating","system","concepts"],
    createdAt: "2026-06-28T17:11:45.333Z",
    views: 55,
    saves: 11,
    offerCount: 0,
  },
  {
    id: "item-gen-23",
    sellerId: "seller-maya",
    sellerName: "Maya",
    sellerAvatar: student1,
    sellerCourse: "Final year IT",
    sellerRating: 4.9,
    title: "Computer Networking (Kurose)",
    description: "Latest edition, practically new.",
    category: "Books" as any,
    condition: "Like new" as any,
    price: 450,
    pickupArea: "Sports Complex",
    images: [productBooks],
    status: "active",
    tags: ["computer","networking","(kurose)"],
    createdAt: "2026-06-17T08:11:45.333Z",
    views: 153,
    saves: 15,
    offerCount: 1,
  },
  {
    id: "item-gen-24",
    sellerId: "seller-aisha",
    sellerName: "Aisha",
    sellerAvatar: student3,
    sellerCourse: "1st year ECE",
    sellerRating: 4.8,
    title: "Computer Networking (Kurose)",
    description: "Latest edition, practically new.",
    category: "Books" as any,
    condition: "Fair" as any,
    price: 650,
    pickupArea: "Canteen Area",
    images: [productBooks],
    status: "active",
    tags: ["computer","networking","(kurose)"],
    createdAt: "2026-06-22T00:11:45.333Z",
    views: 26,
    saves: 3,
    offerCount: 0,
  },
  {
    id: "item-gen-25",
    sellerId: "seller-priya",
    sellerName: "Priya",
    sellerAvatar: student3,
    sellerCourse: "2nd year ECE",
    sellerRating: 4.7,
    title: "Introduction to Algorithms (CLRS)",
    description: "The DSA bible. Heavy book.",
    category: "Books" as any,
    condition: "Used" as any,
    price: 650,
    pickupArea: "Hostel 1",
    images: [productBooks],
    status: "active",
    tags: ["introduction","to","algorithms"],
    createdAt: "2026-06-27T03:11:45.333Z",
    views: 200,
    saves: 14,
    offerCount: 0,
  },
  {
    id: "item-gen-26",
    sellerId: "seller-rahul",
    sellerName: "Rahul",
    sellerAvatar: student2,
    sellerCourse: "4th year Mech",
    sellerRating: 4.6,
    title: "Head First Java",
    description: "Fun read, good for beginners.",
    category: "Books" as any,
    condition: "New" as any,
    price: 250,
    pickupArea: "Girls Hostel Block B",
    images: [productBooks],
    status: "active",
    tags: ["head","first","java"],
    createdAt: "2026-06-27T09:11:45.333Z",
    views: 218,
    saves: 37,
    offerCount: 2,
  },
  {
    id: "item-gen-27",
    sellerId: "seller-nisha",
    sellerName: "Nisha",
    sellerAvatar: student3,
    sellerCourse: "Final year CSE",
    sellerRating: 4.9,
    title: "Head First Java",
    description: "Fun read, good for beginners.",
    category: "Books" as any,
    condition: "Good" as any,
    price: 450,
    pickupArea: "Main Gate",
    images: [productBooks],
    status: "active",
    tags: ["head","first","java"],
    createdAt: "2026-07-04T22:11:45.333Z",
    views: 231,
    saves: 18,
    offerCount: 4,
  },
  {
    id: "item-gen-28",
    sellerId: "seller-aisha",
    sellerName: "Aisha",
    sellerAvatar: student3,
    sellerCourse: "1st year ECE",
    sellerRating: 4.8,
    title: "Python Crash Course",
    description: "Great condition.",
    category: "Books" as any,
    condition: "Fair" as any,
    price: 250,
    pickupArea: "Hostel 4",
    images: [productBooks],
    status: "active",
    tags: ["python","crash","course"],
    createdAt: "2026-07-01T18:11:45.333Z",
    views: 50,
    saves: 8,
    offerCount: 0,
  },
  {
    id: "item-gen-29",
    sellerId: "seller-priya",
    sellerName: "Priya",
    sellerAvatar: student3,
    sellerCourse: "2nd year ECE",
    sellerRating: 4.7,
    title: "Python Crash Course",
    description: "Great condition.",
    category: "Books" as any,
    condition: "Fair" as any,
    price: 400,
    pickupArea: "Hostel 5",
    images: [productBooks],
    status: "active",
    tags: ["python","crash","course"],
    createdAt: "2026-07-05T23:11:45.333Z",
    views: 340,
    saves: 30,
    offerCount: 0,
  },
  {
    id: "item-gen-30",
    sellerId: "seller-rohan",
    sellerName: "Rohan",
    sellerAvatar: student2,
    sellerCourse: "2nd year Mech",
    sellerRating: 4.6,
    title: "Python Crash Course",
    description: "Great condition.",
    category: "Books" as any,
    condition: "New" as any,
    price: 350,
    pickupArea: "Hostel 5",
    images: [productBooks],
    status: "active",
    tags: ["python","crash","course"],
    createdAt: "2026-07-04T15:11:45.333Z",
    views: 16,
    saves: 2,
    offerCount: 0,
  },
  {
    id: "item-gen-31",
    sellerId: "seller-karan",
    sellerName: "Karan",
    sellerAvatar: student2,
    sellerCourse: "1st year Civil",
    sellerRating: 4.5,
    title: "C++ Primer",
    description: "Very detailed.",
    category: "Books" as any,
    condition: "Like new" as any,
    price: 400,
    pickupArea: "Girls Hostel Block B",
    images: [productBooks],
    status: "active",
    tags: ["c++","primer"],
    createdAt: "2026-06-18T22:11:45.333Z",
    views: 170,
    saves: 22,
    offerCount: 1,
  },
  {
    id: "item-gen-32",
    sellerId: "seller-maya",
    sellerName: "Maya",
    sellerAvatar: student1,
    sellerCourse: "Final year IT",
    sellerRating: 4.9,
    title: "C++ Primer",
    description: "Very detailed.",
    category: "Books" as any,
    condition: "Fair" as any,
    price: 500,
    pickupArea: "Hostel 2",
    images: [productBooks],
    status: "active",
    tags: ["c++","primer"],
    createdAt: "2026-06-21T06:11:45.333Z",
    views: 306,
    saves: 45,
    offerCount: 2,
  },
  {
    id: "item-gen-33",
    sellerId: "seller-rahul",
    sellerName: "Rahul",
    sellerAvatar: student2,
    sellerCourse: "4th year Mech",
    sellerRating: 4.6,
    title: "C++ Primer",
    description: "Very detailed.",
    category: "Books" as any,
    condition: "Good" as any,
    price: 500,
    pickupArea: "Hostel 4",
    images: [productBooks],
    status: "active",
    tags: ["c++","primer"],
    createdAt: "2026-07-04T10:11:45.333Z",
    views: 31,
    saves: 5,
    offerCount: 0,
  },
  {
    id: "item-gen-34",
    sellerId: "seller-priya",
    sellerName: "Priya",
    sellerAvatar: student3,
    sellerCourse: "2nd year ECE",
    sellerRating: 4.7,
    title: "Hands-On Machine Learning",
    description: "O'Reilly book, great for ML labs.",
    category: "Books" as any,
    condition: "Fair" as any,
    price: 950,
    pickupArea: "Girls Hostel Block B",
    images: [productBooks],
    status: "active",
    tags: ["hands-on","machine","learning"],
    createdAt: "2026-06-19T12:11:45.333Z",
    views: 273,
    saves: 40,
    offerCount: 1,
  },
  {
    id: "item-gen-35",
    sellerId: "seller-aisha",
    sellerName: "Aisha",
    sellerAvatar: student3,
    sellerCourse: "1st year ECE",
    sellerRating: 4.8,
    title: "Hands-On Machine Learning",
    description: "O'Reilly book, great for ML labs.",
    category: "Books" as any,
    condition: "Good" as any,
    price: 700,
    pickupArea: "Main Gate",
    images: [productBooks],
    status: "sold",
    tags: ["hands-on","machine","learning"],
    createdAt: "2026-07-07T16:11:45.333Z",
    views: 60,
    saves: 3,
    offerCount: 0,
  },
  {
    id: "item-gen-36",
    sellerId: "seller-aisha",
    sellerName: "Aisha",
    sellerAvatar: student3,
    sellerCourse: "1st year ECE",
    sellerRating: 4.8,
    title: "Hands-On Machine Learning",
    description: "O'Reilly book, great for ML labs.",
    category: "Books" as any,
    condition: "Like new" as any,
    price: 900,
    pickupArea: "Mech Block",
    images: [productBooks],
    status: "active",
    tags: ["hands-on","machine","learning"],
    createdAt: "2026-07-02T19:11:45.333Z",
    views: 172,
    saves: 13,
    offerCount: 1,
  },
  {
    id: "item-gen-37",
    sellerId: "seller-rahul",
    sellerName: "Rahul",
    sellerAvatar: student2,
    sellerCourse: "4th year Mech",
    sellerRating: 4.6,
    title: "Higher Engineering Mathematics (B.S. Grewal)",
    description: "Must have for first year.",
    category: "Books" as any,
    condition: "New" as any,
    price: 450,
    pickupArea: "Mech Block",
    images: [productBooks],
    status: "sold",
    tags: ["higher","engineering","mathematics"],
    createdAt: "2026-06-24T13:11:45.333Z",
    views: 123,
    saves: 23,
    offerCount: 3,
  },
  {
    id: "item-gen-38",
    sellerId: "seller-rohan",
    sellerName: "Rohan",
    sellerAvatar: student2,
    sellerCourse: "2nd year Mech",
    sellerRating: 4.6,
    title: "Higher Engineering Mathematics (B.S. Grewal)",
    description: "Must have for first year.",
    category: "Books" as any,
    condition: "Good" as any,
    price: 600,
    pickupArea: "ECE Block",
    images: [productBooks],
    status: "sold",
    tags: ["higher","engineering","mathematics"],
    createdAt: "2026-06-28T06:11:45.333Z",
    views: 268,
    saves: 13,
    offerCount: 2,
  },
  {
    id: "item-gen-39",
    sellerId: "seller-rohan",
    sellerName: "Rohan",
    sellerAvatar: student2,
    sellerCourse: "2nd year Mech",
    sellerRating: 4.6,
    title: "Higher Engineering Mathematics (B.S. Grewal)",
    description: "Must have for first year.",
    category: "Books" as any,
    condition: "Good" as any,
    price: 550,
    pickupArea: "Hostel 1",
    images: [productBooks],
    status: "active",
    tags: ["higher","engineering","mathematics"],
    createdAt: "2026-06-28T13:11:45.333Z",
    views: 387,
    saves: 42,
    offerCount: 11,
  },
  {
    id: "item-gen-40",
    sellerId: "seller-priya",
    sellerName: "Priya",
    sellerAvatar: student3,
    sellerCourse: "2nd year ECE",
    sellerRating: 4.7,
    title: "Complete 3rd Sem CSE Notes",
    description: "Handwritten notes for all subjects.",
    category: "Notes" as any,
    condition: "Used" as any,
    price: 150,
    pickupArea: "ECE Block",
    images: [productBooks],
    status: "active",
    tags: ["complete","3rd","sem"],
    createdAt: "2026-06-18T09:11:45.333Z",
    views: 87,
    saves: 12,
    offerCount: 2,
  },
  {
    id: "item-gen-41",
    sellerId: "seller-nisha",
    sellerName: "Nisha",
    sellerAvatar: student3,
    sellerCourse: "Final year CSE",
    sellerRating: 4.9,
    title: "Physics Lab Manual (Solved)",
    description: "All experiments completed and signed.",
    category: "Notes" as any,
    condition: "New" as any,
    price: 100,
    pickupArea: "Hostel 4",
    images: [productBooks],
    status: "active",
    tags: ["physics","lab","manual"],
    createdAt: "2026-06-17T16:11:45.333Z",
    views: 123,
    saves: 19,
    offerCount: 3,
  },
  {
    id: "item-gen-42",
    sellerId: "seller-arjun",
    sellerName: "Arjun",
    sellerAvatar: student2,
    sellerCourse: "3rd year EEE",
    sellerRating: 4.8,
    title: "First Year Assignment Bundle",
    description: "Reference for all major assignments.",
    category: "Notes" as any,
    condition: "Used" as any,
    price: 250,
    pickupArea: "Hostel 3",
    images: [productBooks],
    status: "sold",
    tags: ["first","year","assignment"],
    createdAt: "2026-06-27T01:11:45.333Z",
    views: 110,
    saves: 7,
    offerCount: 0,
  },
  {
    id: "item-gen-43",
    sellerId: "seller-rahul",
    sellerName: "Rahul",
    sellerAvatar: student2,
    sellerCourse: "4th year Mech",
    sellerRating: 4.6,
    title: "First Year Assignment Bundle",
    description: "Reference for all major assignments.",
    category: "Notes" as any,
    condition: "Used" as any,
    price: 150,
    pickupArea: "CSE Block",
    images: [productBooks],
    status: "active",
    tags: ["first","year","assignment"],
    createdAt: "2026-07-13T16:11:45.333Z",
    views: 206,
    saves: 39,
    offerCount: 11,
  },
  {
    id: "item-gen-44",
    sellerId: "seller-aisha",
    sellerName: "Aisha",
    sellerAvatar: student3,
    sellerCourse: "1st year ECE",
    sellerRating: 4.8,
    title: "Previous Year Papers (Solved, ECE)",
    description: "Last 5 years solved papers.",
    category: "Notes" as any,
    condition: "Used" as any,
    price: 150,
    pickupArea: "Canteen Area",
    images: [productBooks],
    status: "sold",
    tags: ["previous","year","papers"],
    createdAt: "2026-06-21T09:11:45.333Z",
    views: 136,
    saves: 6,
    offerCount: 0,
  },
  {
    id: "item-gen-45",
    sellerId: "seller-sneha",
    sellerName: "Sneha",
    sellerAvatar: student1,
    sellerCourse: "2nd year IT",
    sellerRating: 4.7,
    title: "Previous Year Papers (Solved, ECE)",
    description: "Last 5 years solved papers.",
    category: "Notes" as any,
    condition: "Used" as any,
    price: 200,
    pickupArea: "CSE Block",
    images: [productBooks],
    status: "active",
    tags: ["previous","year","papers"],
    createdAt: "2026-07-10T10:11:45.333Z",
    views: 106,
    saves: 19,
    offerCount: 4,
  },
  {
    id: "item-gen-46",
    sellerId: "seller-arjun",
    sellerName: "Arjun",
    sellerAvatar: student2,
    sellerCourse: "3rd year EEE",
    sellerRating: 4.8,
    title: "Previous Year Papers (Solved, ECE)",
    description: "Last 5 years solved papers.",
    category: "Notes" as any,
    condition: "Like new" as any,
    price: 150,
    pickupArea: "Hostel 1",
    images: [productBooks],
    status: "active",
    tags: ["previous","year","papers"],
    createdAt: "2026-07-12T01:11:45.333Z",
    views: 197,
    saves: 13,
    offerCount: 2,
  },
  {
    id: "item-gen-47",
    sellerId: "seller-arjun",
    sellerName: "Arjun",
    sellerAvatar: student2,
    sellerCourse: "3rd year EEE",
    sellerRating: 4.8,
    title: "Wooden Study Table",
    description: "Foldable, fits in hostel room.",
    category: "Furniture" as any,
    condition: "New" as any,
    price: 1150,
    pickupArea: "Hostel 2",
    images: [productLamp],
    status: "sold",
    tags: ["wooden","study","table"],
    createdAt: "2026-07-02T18:11:45.333Z",
    views: 69,
    saves: 8,
    offerCount: 1,
  },
  {
    id: "item-gen-48",
    sellerId: "seller-arjun",
    sellerName: "Arjun",
    sellerAvatar: student2,
    sellerCourse: "3rd year EEE",
    sellerRating: 4.8,
    title: "Ergonomic Office Chair",
    description: "Good back support for long coding sessions.",
    category: "Furniture" as any,
    condition: "Good" as any,
    price: 2300,
    pickupArea: "CSE Block",
    images: [productLamp],
    status: "active",
    tags: ["ergonomic","office","chair"],
    createdAt: "2026-06-16T13:11:45.333Z",
    views: 135,
    saves: 22,
    offerCount: 0,
  },
  {
    id: "item-gen-49",
    sellerId: "seller-sneha",
    sellerName: "Sneha",
    sellerAvatar: student1,
    sellerCourse: "2nd year IT",
    sellerRating: 4.7,
    title: "Hostel Mattress (Cotton)",
    description: "Clean, used for one semester.",
    category: "Furniture" as any,
    condition: "Good" as any,
    price: 750,
    pickupArea: "Library",
    images: [productLamp],
    status: "active",
    tags: ["hostel","mattress","(cotton)"],
    createdAt: "2026-07-08T05:11:45.333Z",
    views: 146,
    saves: 8,
    offerCount: 0,
  },
  {
    id: "item-gen-50",
    sellerId: "seller-priya",
    sellerName: "Priya",
    sellerAvatar: student3,
    sellerCourse: "2nd year ECE",
    sellerRating: 4.7,
    title: "Hostel Mattress (Cotton)",
    description: "Clean, used for one semester.",
    category: "Furniture" as any,
    condition: "Fair" as any,
    price: 800,
    pickupArea: "Girls Hostel Block B",
    images: [productLamp],
    status: "active",
    tags: ["hostel","mattress","(cotton)"],
    createdAt: "2026-06-19T00:11:45.333Z",
    views: 209,
    saves: 18,
    offerCount: 0,
  },
  {
    id: "item-gen-51",
    sellerId: "seller-jordan",
    sellerName: "Jordan",
    sellerAvatar: student2,
    sellerCourse: "3rd year CSE",
    sellerRating: 4.8,
    title: "Small Bookshelf",
    description: "Holds about 20 books.",
    category: "Furniture" as any,
    condition: "New" as any,
    price: 400,
    pickupArea: "Hostel 4",
    images: [productLamp],
    status: "active",
    tags: ["small","bookshelf"],
    createdAt: "2026-06-28T17:11:45.333Z",
    views: 77,
    saves: 8,
    offerCount: 0,
  },
  {
    id: "item-gen-52",
    sellerId: "seller-karan",
    sellerName: "Karan",
    sellerAvatar: student2,
    sellerCourse: "1st year Civil",
    sellerRating: 4.5,
    title: "Plastic Wardrobe/Drawer",
    description: "3-tier drawer.",
    category: "Furniture" as any,
    condition: "Fair" as any,
    price: 950,
    pickupArea: "Girls Hostel Block A",
    images: [productLamp],
    status: "active",
    tags: ["plastic","wardrobe/drawer"],
    createdAt: "2026-06-27T16:11:45.333Z",
    views: 385,
    saves: 23,
    offerCount: 4,
  },
  {
    id: "item-gen-53",
    sellerId: "seller-arjun",
    sellerName: "Arjun",
    sellerAvatar: student2,
    sellerCourse: "3rd year EEE",
    sellerRating: 4.8,
    title: "Plastic Wardrobe/Drawer",
    description: "3-tier drawer.",
    category: "Furniture" as any,
    condition: "New" as any,
    price: 1050,
    pickupArea: "Hostel 1",
    images: [productLamp],
    status: "active",
    tags: ["plastic","wardrobe/drawer"],
    createdAt: "2026-06-18T21:11:45.333Z",
    views: 109,
    saves: 5,
    offerCount: 0,
  },
  {
    id: "item-gen-54",
    sellerId: "seller-arjun",
    sellerName: "Arjun",
    sellerAvatar: student2,
    sellerCourse: "3rd year EEE",
    sellerRating: 4.8,
    title: "Study Lamp (LED)",
    description: "Rechargeable.",
    category: "Furniture" as any,
    condition: "Good" as any,
    price: 450,
    pickupArea: "Hostel 1",
    images: [productLamp],
    status: "active",
    tags: ["study","lamp","(led)"],
    createdAt: "2026-07-05T00:11:45.333Z",
    views: 12,
    saves: 1,
    offerCount: 0,
  },
  {
    id: "item-gen-55",
    sellerId: "seller-aisha",
    sellerName: "Aisha",
    sellerAvatar: student3,
    sellerCourse: "1st year ECE",
    sellerRating: 4.8,
    title: "Full Length Mirror",
    description: "Can be hung on door.",
    category: "Furniture" as any,
    condition: "Fair" as any,
    price: 400,
    pickupArea: "Hostel 4",
    images: [productLamp],
    status: "active",
    tags: ["full","length","mirror"],
    createdAt: "2026-07-02T14:11:45.333Z",
    views: 9,
    saves: 1,
    offerCount: 0,
  },
  {
    id: "item-gen-56",
    sellerId: "seller-rohan",
    sellerName: "Rohan",
    sellerAvatar: student2,
    sellerCourse: "2nd year Mech",
    sellerRating: 4.6,
    title: "Full Length Mirror",
    description: "Can be hung on door.",
    category: "Furniture" as any,
    condition: "Fair" as any,
    price: 350,
    pickupArea: "Library",
    images: [productLamp],
    status: "active",
    tags: ["full","length","mirror"],
    createdAt: "2026-07-13T07:11:45.333Z",
    views: 300,
    saves: 48,
    offerCount: 6,
  },
  {
    id: "item-gen-57",
    sellerId: "seller-aisha",
    sellerName: "Aisha",
    sellerAvatar: student3,
    sellerCourse: "1st year ECE",
    sellerRating: 4.8,
    title: "Full Length Mirror",
    description: "Can be hung on door.",
    category: "Furniture" as any,
    condition: "Used" as any,
    price: 450,
    pickupArea: "Hostel 2",
    images: [productLamp],
    status: "active",
    tags: ["full","length","mirror"],
    createdAt: "2026-07-12T12:11:45.333Z",
    views: 76,
    saves: 11,
    offerCount: 1,
  },
  {
    id: "item-gen-58",
    sellerId: "seller-priya",
    sellerName: "Priya",
    sellerAvatar: student3,
    sellerCourse: "2nd year ECE",
    sellerRating: 4.7,
    title: "Hero Sprint Pro",
    description: "Geared cycle. Needs air.",
    category: "Cycles" as any,
    condition: "Fair" as any,
    price: 4200,
    pickupArea: "Main Gate",
    images: [productBike],
    status: "active",
    tags: ["hero","sprint","pro"],
    createdAt: "2026-06-28T11:11:45.333Z",
    views: 86,
    saves: 17,
    offerCount: 2,
  },
  {
    id: "item-gen-59",
    sellerId: "seller-priya",
    sellerName: "Priya",
    sellerAvatar: student3,
    sellerCourse: "2nd year ECE",
    sellerRating: 4.7,
    title: "Firefox Meteor",
    description: "Well maintained, recently serviced.",
    category: "Cycles" as any,
    condition: "New" as any,
    price: 6100,
    pickupArea: "Girls Hostel Block B",
    images: [productBike],
    status: "active",
    tags: ["firefox","meteor"],
    createdAt: "2026-07-10T14:11:45.333Z",
    views: 22,
    saves: 2,
    offerCount: 0,
  },
  {
    id: "item-gen-60",
    sellerId: "seller-jordan",
    sellerName: "Jordan",
    sellerAvatar: student2,
    sellerCourse: "3rd year CSE",
    sellerRating: 4.8,
    title: "Firefox Meteor",
    description: "Well maintained, recently serviced.",
    category: "Cycles" as any,
    condition: "Good" as any,
    price: 5650,
    pickupArea: "Mech Block",
    images: [productBike],
    status: "sold",
    tags: ["firefox","meteor"],
    createdAt: "2026-07-01T23:11:45.333Z",
    views: 157,
    saves: 31,
    offerCount: 6,
  },
  {
    id: "item-gen-61",
    sellerId: "seller-rohan",
    sellerName: "Rohan",
    sellerAvatar: student2,
    sellerCourse: "2nd year Mech",
    sellerRating: 4.6,
    title: "Hercules Roadeo MTB",
    description: "Good suspension.",
    category: "Cycles" as any,
    condition: "Good" as any,
    price: 3500,
    pickupArea: "Girls Hostel Block A",
    images: [productBike],
    status: "active",
    tags: ["hercules","roadeo","mtb"],
    createdAt: "2026-07-11T21:11:45.333Z",
    views: 208,
    saves: 39,
    offerCount: 9,
  },
  {
    id: "item-gen-62",
    sellerId: "seller-rohan",
    sellerName: "Rohan",
    sellerAvatar: student2,
    sellerCourse: "2nd year Mech",
    sellerRating: 4.6,
    title: "Hercules Roadeo MTB",
    description: "Good suspension.",
    category: "Cycles" as any,
    condition: "Fair" as any,
    price: 4300,
    pickupArea: "Gate 2",
    images: [productBike],
    status: "active",
    tags: ["hercules","roadeo","mtb"],
    createdAt: "2026-07-13T03:11:45.333Z",
    views: 184,
    saves: 31,
    offerCount: 6,
  },
  {
    id: "item-gen-63",
    sellerId: "seller-karan",
    sellerName: "Karan",
    sellerAvatar: student2,
    sellerCourse: "1st year Civil",
    sellerRating: 4.5,
    title: "Atlas Campus Cycle",
    description: "Single speed, reliable.",
    category: "Cycles" as any,
    condition: "Used" as any,
    price: 2800,
    pickupArea: "Hostel 1",
    images: [productBike],
    status: "active",
    tags: ["atlas","campus","cycle"],
    createdAt: "2026-06-27T00:11:45.333Z",
    views: 190,
    saves: 9,
    offerCount: 0,
  },
  {
    id: "item-gen-64",
    sellerId: "seller-rohan",
    sellerName: "Rohan",
    sellerAvatar: student2,
    sellerCourse: "2nd year Mech",
    sellerRating: 4.6,
    title: "Plastic Bucket & Mug Set",
    description: "Unused.",
    category: "Hostel Essentials" as any,
    condition: "New" as any,
    price: 200,
    pickupArea: "Library",
    images: [productLamp],
    status: "active",
    tags: ["plastic","bucket","&"],
    createdAt: "2026-07-06T18:11:45.333Z",
    views: 293,
    saves: 20,
    offerCount: 4,
  },
  {
    id: "item-gen-65",
    sellerId: "seller-rahul",
    sellerName: "Rahul",
    sellerAvatar: student2,
    sellerCourse: "4th year Mech",
    sellerRating: 4.6,
    title: "Plastic Bucket & Mug Set",
    description: "Unused.",
    category: "Hostel Essentials" as any,
    condition: "New" as any,
    price: 150,
    pickupArea: "Gate 2",
    images: [productLamp],
    status: "active",
    tags: ["plastic","bucket","&"],
    createdAt: "2026-07-11T03:11:45.333Z",
    views: 390,
    saves: 46,
    offerCount: 7,
  },
  {
    id: "item-gen-66",
    sellerId: "seller-aisha",
    sellerName: "Aisha",
    sellerAvatar: student3,
    sellerCourse: "1st year ECE",
    sellerRating: 4.8,
    title: "Plastic Bucket & Mug Set",
    description: "Unused.",
    category: "Hostel Essentials" as any,
    condition: "Used" as any,
    price: 150,
    pickupArea: "CSE Block",
    images: [productLamp],
    status: "sold",
    tags: ["plastic","bucket","&"],
    createdAt: "2026-07-08T23:11:45.333Z",
    views: 327,
    saves: 65,
    offerCount: 17,
  },
  {
    id: "item-gen-67",
    sellerId: "seller-sneha",
    sellerName: "Sneha",
    sellerAvatar: student1,
    sellerCourse: "2nd year IT",
    sellerRating: 4.7,
    title: "Electric Kettle (1L)",
    description: "Makes maggi perfectly.",
    category: "Hostel Essentials" as any,
    condition: "Fair" as any,
    price: 550,
    pickupArea: "CSE Block",
    images: [productLamp],
    status: "active",
    tags: ["electric","kettle","(1l)"],
    createdAt: "2026-07-10T17:11:45.333Z",
    views: 135,
    saves: 6,
    offerCount: 0,
  },
  {
    id: "item-gen-68",
    sellerId: "seller-arjun",
    sellerName: "Arjun",
    sellerAvatar: student2,
    sellerCourse: "3rd year EEE",
    sellerRating: 4.8,
    title: "Electric Kettle (1L)",
    description: "Makes maggi perfectly.",
    category: "Hostel Essentials" as any,
    condition: "Used" as any,
    price: 400,
    pickupArea: "Sports Complex",
    images: [productLamp],
    status: "active",
    tags: ["electric","kettle","(1l)"],
    createdAt: "2026-06-26T14:11:45.333Z",
    views: 171,
    saves: 18,
    offerCount: 4,
  },
  {
    id: "item-gen-69",
    sellerId: "seller-sneha",
    sellerName: "Sneha",
    sellerAvatar: student1,
    sellerCourse: "2nd year IT",
    sellerRating: 4.7,
    title: "Induction Cooktop (Pigeon)",
    description: "Works well.",
    category: "Hostel Essentials" as any,
    condition: "Good" as any,
    price: 1000,
    pickupArea: "Girls Hostel Block A",
    images: [productLamp],
    status: "active",
    tags: ["induction","cooktop","(pigeon)"],
    createdAt: "2026-06-23T15:11:45.333Z",
    views: 128,
    saves: 25,
    offerCount: 7,
  },
  {
    id: "item-gen-70",
    sellerId: "seller-priya",
    sellerName: "Priya",
    sellerAvatar: student3,
    sellerCourse: "2nd year ECE",
    sellerRating: 4.7,
    title: "Extension Board (4 sockets)",
    description: "Surge protected.",
    category: "Hostel Essentials" as any,
    condition: "Fair" as any,
    price: 200,
    pickupArea: "Library",
    images: [productLamp],
    status: "active",
    tags: ["extension","board","(4"],
    createdAt: "2026-06-23T15:11:45.333Z",
    views: 115,
    saves: 23,
    offerCount: 3,
  },
  {
    id: "item-gen-71",
    sellerId: "seller-arjun",
    sellerName: "Arjun",
    sellerAvatar: student2,
    sellerCourse: "3rd year EEE",
    sellerRating: 4.8,
    title: "Extension Board (4 sockets)",
    description: "Surge protected.",
    category: "Hostel Essentials" as any,
    condition: "Good" as any,
    price: 250,
    pickupArea: "Hostel 5",
    images: [productLamp],
    status: "active",
    tags: ["extension","board","(4"],
    createdAt: "2026-06-16T13:11:45.333Z",
    views: 350,
    saves: 17,
    offerCount: 4,
  },
  {
    id: "item-gen-72",
    sellerId: "seller-maya",
    sellerName: "Maya",
    sellerAvatar: student1,
    sellerCourse: "Final year IT",
    sellerRating: 4.9,
    title: "Table Fan (Usha)",
    description: "Life saver in summer.",
    category: "Hostel Essentials" as any,
    condition: "Fair" as any,
    price: 900,
    pickupArea: "Girls Hostel Block B",
    images: [productLamp],
    status: "active",
    tags: ["table","fan","(usha)"],
    createdAt: "2026-06-26T10:11:45.333Z",
    views: 393,
    saves: 55,
    offerCount: 7,
  },
  {
    id: "item-gen-73",
    sellerId: "seller-sneha",
    sellerName: "Sneha",
    sellerAvatar: student1,
    sellerCourse: "2nd year IT",
    sellerRating: 4.7,
    title: "Table Fan (Usha)",
    description: "Life saver in summer.",
    category: "Hostel Essentials" as any,
    condition: "Fair" as any,
    price: 900,
    pickupArea: "Gate 2",
    images: [productLamp],
    status: "active",
    tags: ["table","fan","(usha)"],
    createdAt: "2026-07-03T05:11:45.333Z",
    views: 396,
    saves: 39,
    offerCount: 5,
  },
  {
    id: "item-gen-74",
    sellerId: "seller-karan",
    sellerName: "Karan",
    sellerAvatar: student2,
    sellerCourse: "1st year Civil",
    sellerRating: 4.5,
    title: "Electric Iron (Philips)",
    description: "Lightweight.",
    category: "Hostel Essentials" as any,
    condition: "Good" as any,
    price: 550,
    pickupArea: "Girls Hostel Block B",
    images: [productLamp],
    status: "active",
    tags: ["electric","iron","(philips)"],
    createdAt: "2026-07-04T19:11:45.333Z",
    views: 337,
    saves: 50,
    offerCount: 6,
  },
  {
    id: "item-gen-75",
    sellerId: "seller-aisha",
    sellerName: "Aisha",
    sellerAvatar: student3,
    sellerCourse: "1st year ECE",
    sellerRating: 4.8,
    title: "Milton Thermos Bottle",
    description: "Keeps water hot/cold.",
    category: "Hostel Essentials" as any,
    condition: "Like new" as any,
    price: 250,
    pickupArea: "Mech Block",
    images: [productLamp],
    status: "active",
    tags: ["milton","thermos","bottle"],
    createdAt: "2026-06-24T19:11:45.333Z",
    views: 228,
    saves: 31,
    offerCount: 8,
  },
  {
    id: "item-gen-76",
    sellerId: "seller-arjun",
    sellerName: "Arjun",
    sellerAvatar: student2,
    sellerCourse: "3rd year EEE",
    sellerRating: 4.8,
    title: "Milton Thermos Bottle",
    description: "Keeps water hot/cold.",
    category: "Hostel Essentials" as any,
    condition: "Like new" as any,
    price: 200,
    pickupArea: "Main Gate",
    images: [productLamp],
    status: "active",
    tags: ["milton","thermos","bottle"],
    createdAt: "2026-06-26T02:11:45.333Z",
    views: 288,
    saves: 14,
    offerCount: 0,
  },
  {
    id: "item-gen-77",
    sellerId: "seller-maya",
    sellerName: "Maya",
    sellerAvatar: student1,
    sellerCourse: "Final year IT",
    sellerRating: 4.9,
    title: "Milton Thermos Bottle",
    description: "Keeps water hot/cold.",
    category: "Hostel Essentials" as any,
    condition: "New" as any,
    price: 350,
    pickupArea: "ECE Block",
    images: [productLamp],
    status: "active",
    tags: ["milton","thermos","bottle"],
    createdAt: "2026-07-12T17:11:45.333Z",
    views: 303,
    saves: 60,
    offerCount: 16,
  },
  {
    id: "item-gen-78",
    sellerId: "seller-priya",
    sellerName: "Priya",
    sellerAvatar: student3,
    sellerCourse: "2nd year ECE",
    sellerRating: 4.7,
    title: "College Fest Hoodie (Size L)",
    description: "Official merch.",
    category: "Clothing" as any,
    condition: "Good" as any,
    price: 500,
    pickupArea: "Hostel 2",
    images: [productBooks],
    status: "active",
    tags: ["college","fest","hoodie"],
    createdAt: "2026-06-14T00:11:45.333Z",
    views: 225,
    saves: 15,
    offerCount: 3,
  },
  {
    id: "item-gen-79",
    sellerId: "seller-arjun",
    sellerName: "Arjun",
    sellerAvatar: student2,
    sellerCourse: "3rd year EEE",
    sellerRating: 4.8,
    title: "College Fest Hoodie (Size L)",
    description: "Official merch.",
    category: "Clothing" as any,
    condition: "Good" as any,
    price: 450,
    pickupArea: "Library",
    images: [productBooks],
    status: "active",
    tags: ["college","fest","hoodie"],
    createdAt: "2026-06-16T20:11:45.333Z",
    views: 175,
    saves: 31,
    offerCount: 3,
  },
  {
    id: "item-gen-80",
    sellerId: "seller-sneha",
    sellerName: "Sneha",
    sellerAvatar: student1,
    sellerCourse: "2nd year IT",
    sellerRating: 4.7,
    title: "College Fest Hoodie (Size L)",
    description: "Official merch.",
    category: "Clothing" as any,
    condition: "New" as any,
    price: 550,
    pickupArea: "Mech Block",
    images: [productBooks],
    status: "sold",
    tags: ["college","fest","hoodie"],
    createdAt: "2026-06-17T22:11:45.333Z",
    views: 350,
    saves: 28,
    offerCount: 1,
  },
  {
    id: "item-gen-81",
    sellerId: "seller-sneha",
    sellerName: "Sneha",
    sellerAvatar: student1,
    sellerCourse: "2nd year IT",
    sellerRating: 4.7,
    title: "Denim Jacket (Size M)",
    description: "Barely worn.",
    category: "Clothing" as any,
    condition: "Good" as any,
    price: 450,
    pickupArea: "Girls Hostel Block A",
    images: [productBooks],
    status: "active",
    tags: ["denim","jacket","(size"],
    createdAt: "2026-07-12T17:11:45.333Z",
    views: 230,
    saves: 36,
    offerCount: 5,
  },
  {
    id: "item-gen-82",
    sellerId: "seller-maya",
    sellerName: "Maya",
    sellerAvatar: student1,
    sellerCourse: "Final year IT",
    sellerRating: 4.9,
    title: "Denim Jacket (Size M)",
    description: "Barely worn.",
    category: "Clothing" as any,
    condition: "New" as any,
    price: 550,
    pickupArea: "Hostel 4",
    images: [productBooks],
    status: "active",
    tags: ["denim","jacket","(size"],
    createdAt: "2026-06-21T12:11:45.333Z",
    views: 252,
    saves: 40,
    offerCount: 11,
  },
  {
    id: "item-gen-83",
    sellerId: "seller-rohan",
    sellerName: "Rohan",
    sellerAvatar: student2,
    sellerCourse: "2nd year Mech",
    sellerRating: 4.6,
    title: "Denim Jacket (Size M)",
    description: "Barely worn.",
    category: "Clothing" as any,
    condition: "New" as any,
    price: 650,
    pickupArea: "Girls Hostel Block A",
    images: [productBooks],
    status: "active",
    tags: ["denim","jacket","(size"],
    createdAt: "2026-06-28T16:11:45.333Z",
    views: 140,
    saves: 19,
    offerCount: 1,
  },
  {
    id: "item-gen-84",
    sellerId: "seller-sneha",
    sellerName: "Sneha",
    sellerAvatar: student1,
    sellerCourse: "2nd year IT",
    sellerRating: 4.7,
    title: "Levis Jeans (32)",
    description: "Blue, straight fit.",
    category: "Clothing" as any,
    condition: "New" as any,
    price: 650,
    pickupArea: "Library",
    images: [productBooks],
    status: "sold",
    tags: ["levis","jeans","(32)"],
    createdAt: "2026-06-29T22:11:45.333Z",
    views: 50,
    saves: 3,
    offerCount: 0,
  },
  {
    id: "item-gen-85",
    sellerId: "seller-rahul",
    sellerName: "Rahul",
    sellerAvatar: student2,
    sellerCourse: "4th year Mech",
    sellerRating: 4.6,
    title: "Puma Running Shoes (UK 9)",
    description: "Good for gym.",
    category: "Clothing" as any,
    condition: "New" as any,
    price: 1150,
    pickupArea: "Hostel 2",
    images: [productBooks],
    status: "active",
    tags: ["puma","running","shoes"],
    createdAt: "2026-07-08T14:11:45.333Z",
    views: 53,
    saves: 7,
    offerCount: 1,
  },
  {
    id: "item-gen-86",
    sellerId: "seller-sneha",
    sellerName: "Sneha",
    sellerAvatar: student1,
    sellerCourse: "2nd year IT",
    sellerRating: 4.7,
    title: "Wildcraft Backpack",
    description: "Has laptop sleeve.",
    category: "Clothing" as any,
    condition: "Like new" as any,
    price: 700,
    pickupArea: "Hostel 5",
    images: [productBooks],
    status: "active",
    tags: ["wildcraft","backpack"],
    createdAt: "2026-06-24T02:11:45.334Z",
    views: 152,
    saves: 13,
    offerCount: 3,
  },
  {
    id: "item-gen-87",
    sellerId: "seller-maya",
    sellerName: "Maya",
    sellerAvatar: student1,
    sellerCourse: "Final year IT",
    sellerRating: 4.9,
    title: "Wildcraft Backpack",
    description: "Has laptop sleeve.",
    category: "Clothing" as any,
    condition: "Used" as any,
    price: 500,
    pickupArea: "Girls Hostel Block A",
    images: [productBooks],
    status: "sold",
    tags: ["wildcraft","backpack"],
    createdAt: "2026-06-22T01:11:45.334Z",
    views: 238,
    saves: 38,
    offerCount: 4,
  },
  {
    id: "item-gen-88",
    sellerId: "seller-jordan",
    sellerName: "Jordan",
    sellerAvatar: student2,
    sellerCourse: "3rd year CSE",
    sellerRating: 4.8,
    title: "Wildcraft Backpack",
    description: "Has laptop sleeve.",
    category: "Clothing" as any,
    condition: "New" as any,
    price: 400,
    pickupArea: "Library",
    images: [productBooks],
    status: "sold",
    tags: ["wildcraft","backpack"],
    createdAt: "2026-07-04T03:11:45.334Z",
    views: 232,
    saves: 18,
    offerCount: 0,
  },
  {
    id: "item-gen-89",
    sellerId: "seller-karan",
    sellerName: "Karan",
    sellerAvatar: student2,
    sellerCourse: "1st year Civil",
    sellerRating: 4.5,
    title: "Nivia Football (Size 5)",
    description: "Used on turf.",
    category: "Sports" as any,
    condition: "Like new" as any,
    price: 300,
    pickupArea: "Hostel 3",
    images: [productBike],
    status: "active",
    tags: ["nivia","football","(size"],
    createdAt: "2026-07-03T07:11:45.334Z",
    views: 75,
    saves: 14,
    offerCount: 4,
  },
  {
    id: "item-gen-90",
    sellerId: "seller-arjun",
    sellerName: "Arjun",
    sellerAvatar: student2,
    sellerCourse: "3rd year EEE",
    sellerRating: 4.8,
    title: "Nivia Football (Size 5)",
    description: "Used on turf.",
    category: "Sports" as any,
    condition: "Fair" as any,
    price: 250,
    pickupArea: "Canteen Area",
    images: [productBike],
    status: "active",
    tags: ["nivia","football","(size"],
    createdAt: "2026-06-29T10:11:45.334Z",
    views: 147,
    saves: 14,
    offerCount: 0,
  },
  {
    id: "item-gen-91",
    sellerId: "seller-karan",
    sellerName: "Karan",
    sellerAvatar: student2,
    sellerCourse: "1st year Civil",
    sellerRating: 4.5,
    title: "Kashmir Willow Cricket Bat",
    description: "Good stroke.",
    category: "Sports" as any,
    condition: "New" as any,
    price: 550,
    pickupArea: "Mech Block",
    images: [productBike],
    status: "active",
    tags: ["kashmir","willow","cricket"],
    createdAt: "2026-06-26T07:11:45.334Z",
    views: 95,
    saves: 13,
    offerCount: 0,
  },
  {
    id: "item-gen-92",
    sellerId: "seller-sneha",
    sellerName: "Sneha",
    sellerAvatar: student1,
    sellerCourse: "2nd year IT",
    sellerRating: 4.7,
    title: "Kashmir Willow Cricket Bat",
    description: "Good stroke.",
    category: "Sports" as any,
    condition: "Fair" as any,
    price: 950,
    pickupArea: "Hostel 5",
    images: [productBike],
    status: "active",
    tags: ["kashmir","willow","cricket"],
    createdAt: "2026-06-29T04:11:45.334Z",
    views: 176,
    saves: 33,
    offerCount: 8,
  },
  {
    id: "item-gen-93",
    sellerId: "seller-rohan",
    sellerName: "Rohan",
    sellerAvatar: student2,
    sellerCourse: "2nd year Mech",
    sellerRating: 4.6,
    title: "Kashmir Willow Cricket Bat",
    description: "Good stroke.",
    category: "Sports" as any,
    condition: "Good" as any,
    price: 800,
    pickupArea: "Main Gate",
    images: [productBike],
    status: "sold",
    tags: ["kashmir","willow","cricket"],
    createdAt: "2026-07-03T17:11:45.334Z",
    views: 362,
    saves: 72,
    offerCount: 6,
  },
  {
    id: "item-gen-94",
    sellerId: "seller-priya",
    sellerName: "Priya",
    sellerAvatar: student3,
    sellerCourse: "2nd year ECE",
    sellerRating: 4.7,
    title: "Yonex Badminton Racket",
    description: "Grip needs replacement.",
    category: "Sports" as any,
    condition: "Like new" as any,
    price: 650,
    pickupArea: "Gate 2",
    images: [productBike],
    status: "active",
    tags: ["yonex","badminton","racket"],
    createdAt: "2026-06-29T05:11:45.334Z",
    views: 125,
    saves: 12,
    offerCount: 0,
  },
  {
    id: "item-gen-95",
    sellerId: "seller-karan",
    sellerName: "Karan",
    sellerAvatar: student2,
    sellerCourse: "1st year Civil",
    sellerRating: 4.5,
    title: "Dumbbells (5kg Pair)",
    description: "Hex rubber.",
    category: "Sports" as any,
    condition: "Fair" as any,
    price: 700,
    pickupArea: "Library",
    images: [productBike],
    status: "active",
    tags: ["dumbbells","(5kg","pair)"],
    createdAt: "2026-07-03T13:11:45.334Z",
    views: 96,
    saves: 5,
    offerCount: 0,
  },
  {
    id: "item-gen-96",
    sellerId: "seller-rahul",
    sellerName: "Rahul",
    sellerAvatar: student2,
    sellerCourse: "4th year Mech",
    sellerRating: 4.6,
    title: "Dumbbells (5kg Pair)",
    description: "Hex rubber.",
    category: "Sports" as any,
    condition: "Used" as any,
    price: 550,
    pickupArea: "Hostel 3",
    images: [productBike],
    status: "active",
    tags: ["dumbbells","(5kg","pair)"],
    createdAt: "2026-06-15T04:11:45.334Z",
    views: 287,
    saves: 45,
    offerCount: 5,
  },
  {
    id: "item-gen-97",
    sellerId: "seller-priya",
    sellerName: "Priya",
    sellerAvatar: student3,
    sellerCourse: "2nd year ECE",
    sellerRating: 4.7,
    title: "Dumbbells (5kg Pair)",
    description: "Hex rubber.",
    category: "Sports" as any,
    condition: "Used" as any,
    price: 650,
    pickupArea: "Mech Block",
    images: [productBike],
    status: "active",
    tags: ["dumbbells","(5kg","pair)"],
    createdAt: "2026-07-07T12:11:45.334Z",
    views: 11,
    saves: 0,
    offerCount: 0,
  },
  {
    id: "item-gen-98",
    sellerId: "seller-karan",
    sellerName: "Karan",
    sellerAvatar: student2,
    sellerCourse: "1st year Civil",
    sellerRating: 4.5,
    title: "Yoga Mat",
    description: "Anti-slip.",
    category: "Sports" as any,
    condition: "Used" as any,
    price: 150,
    pickupArea: "Gate 2",
    images: [productBike],
    status: "active",
    tags: ["yoga","mat"],
    createdAt: "2026-07-02T14:11:45.334Z",
    views: 289,
    saves: 20,
    offerCount: 1,
  },
  {
    id: "item-gen-99",
    sellerId: "seller-jordan",
    sellerName: "Jordan",
    sellerAvatar: student2,
    sellerCourse: "3rd year CSE",
    sellerRating: 4.8,
    title: "Yoga Mat",
    description: "Anti-slip.",
    category: "Sports" as any,
    condition: "New" as any,
    price: 300,
    pickupArea: "CSE Block",
    images: [productBike],
    status: "active",
    tags: ["yoga","mat"],
    createdAt: "2026-07-11T04:11:45.334Z",
    views: 74,
    saves: 6,
    offerCount: 0,
  },
  {
    id: "item-gen-100",
    sellerId: "seller-rohan",
    sellerName: "Rohan",
    sellerAvatar: student2,
    sellerCourse: "2nd year Mech",
    sellerRating: 4.6,
    title: "Casio Vintage Watch",
    description: "Silver, classic.",
    category: "Accessories" as any,
    condition: "Good" as any,
    price: 1150,
    pickupArea: "Gate 2",
    images: [productLaptop],
    status: "active",
    tags: ["casio","vintage","watch"],
    createdAt: "2026-07-05T12:11:45.334Z",
    views: 251,
    saves: 32,
    offerCount: 2,
  },
  {
    id: "item-gen-101",
    sellerId: "seller-priya",
    sellerName: "Priya",
    sellerAvatar: student3,
    sellerCourse: "2nd year ECE",
    sellerRating: 4.7,
    title: "Casio Vintage Watch",
    description: "Silver, classic.",
    category: "Accessories" as any,
    condition: "New" as any,
    price: 1100,
    pickupArea: "Hostel 4",
    images: [productLaptop],
    status: "active",
    tags: ["casio","vintage","watch"],
    createdAt: "2026-06-15T13:11:45.334Z",
    views: 294,
    saves: 23,
    offerCount: 6,
  },
  {
    id: "item-gen-102",
    sellerId: "seller-rahul",
    sellerName: "Rahul",
    sellerAvatar: student2,
    sellerCourse: "4th year Mech",
    sellerRating: 4.6,
    title: "Casio Vintage Watch",
    description: "Silver, classic.",
    category: "Accessories" as any,
    condition: "New" as any,
    price: 1500,
    pickupArea: "Hostel 1",
    images: [productLaptop],
    status: "sold",
    tags: ["casio","vintage","watch"],
    createdAt: "2026-06-26T19:11:45.334Z",
    views: 158,
    saves: 31,
    offerCount: 5,
  },
  {
    id: "item-gen-103",
    sellerId: "seller-karan",
    sellerName: "Karan",
    sellerAvatar: student2,
    sellerCourse: "1st year Civil",
    sellerRating: 4.5,
    title: "Boat Wired Earphones",
    description: "Bass is good.",
    category: "Accessories" as any,
    condition: "Used" as any,
    price: 200,
    pickupArea: "Hostel 2",
    images: [productLaptop],
    status: "active",
    tags: ["boat","wired","earphones"],
    createdAt: "2026-06-30T19:11:45.334Z",
    views: 385,
    saves: 73,
    offerCount: 21,
  },
  {
    id: "item-gen-104",
    sellerId: "seller-karan",
    sellerName: "Karan",
    sellerAvatar: student2,
    sellerCourse: "1st year Civil",
    sellerRating: 4.5,
    title: "Boat Wired Earphones",
    description: "Bass is good.",
    category: "Accessories" as any,
    condition: "Like new" as any,
    price: 250,
    pickupArea: "Gate 2",
    images: [productLaptop],
    status: "active",
    tags: ["boat","wired","earphones"],
    createdAt: "2026-06-17T11:11:45.334Z",
    views: 105,
    saves: 17,
    offerCount: 3,
  },
  {
    id: "item-gen-105",
    sellerId: "seller-aisha",
    sellerName: "Aisha",
    sellerAvatar: student3,
    sellerCourse: "1st year ECE",
    sellerRating: 4.8,
    title: "Boat Wired Earphones",
    description: "Bass is good.",
    category: "Accessories" as any,
    condition: "Used" as any,
    price: 250,
    pickupArea: "Gate 2",
    images: [productLaptop],
    status: "active",
    tags: ["boat","wired","earphones"],
    createdAt: "2026-07-11T22:11:45.334Z",
    views: 270,
    saves: 43,
    offerCount: 12,
  },
  {
    id: "item-gen-106",
    sellerId: "seller-aisha",
    sellerName: "Aisha",
    sellerAvatar: student3,
    sellerCourse: "1st year ECE",
    sellerRating: 4.8,
    title: "Aluminum Laptop Stand",
    description: "Adjustable height.",
    category: "Accessories" as any,
    condition: "Like new" as any,
    price: 350,
    pickupArea: "Hostel 4",
    images: [productLaptop],
    status: "sold",
    tags: ["aluminum","laptop","stand"],
    createdAt: "2026-06-23T09:11:45.334Z",
    views: 66,
    saves: 5,
    offerCount: 0,
  },
  {
    id: "item-gen-107",
    sellerId: "seller-aisha",
    sellerName: "Aisha",
    sellerAvatar: student3,
    sellerCourse: "1st year ECE",
    sellerRating: 4.8,
    title: "Aluminum Laptop Stand",
    description: "Adjustable height.",
    category: "Accessories" as any,
    condition: "New" as any,
    price: 500,
    pickupArea: "Girls Hostel Block B",
    images: [productLaptop],
    status: "sold",
    tags: ["aluminum","laptop","stand"],
    createdAt: "2026-07-12T09:11:45.334Z",
    views: 298,
    saves: 26,
    offerCount: 2,
  },
  {
    id: "item-gen-108",
    sellerId: "seller-karan",
    sellerName: "Karan",
    sellerAvatar: student2,
    sellerCourse: "1st year Civil",
    sellerRating: 4.5,
    title: "Extended Mouse Pad",
    description: "World map design.",
    category: "Accessories" as any,
    condition: "Like new" as any,
    price: 200,
    pickupArea: "ECE Block",
    images: [productLaptop],
    status: "active",
    tags: ["extended","mouse","pad"],
    createdAt: "2026-06-20T04:11:45.334Z",
    views: 375,
    saves: 33,
    offerCount: 2,
  },
  {
    id: "item-gen-109",
    sellerId: "seller-sneha",
    sellerName: "Sneha",
    sellerAvatar: student1,
    sellerCourse: "2nd year IT",
    sellerRating: 4.7,
    title: "USB C Hub (4 ports)",
    description: "Has HDMI.",
    category: "Accessories" as any,
    condition: "Used" as any,
    price: 700,
    pickupArea: "Girls Hostel Block A",
    images: [productLaptop],
    status: "sold",
    tags: ["usb","c","hub"],
    createdAt: "2026-06-29T02:11:45.334Z",
    views: 8,
    saves: 0,
    offerCount: 0,
  },
  {
    id: "item-gen-110",
    sellerId: "seller-rahul",
    sellerName: "Rahul",
    sellerAvatar: student2,
    sellerCourse: "4th year Mech",
    sellerRating: 4.6,
    title: "USB C Hub (4 ports)",
    description: "Has HDMI.",
    category: "Accessories" as any,
    condition: "New" as any,
    price: 500,
    pickupArea: "Girls Hostel Block B",
    images: [productLaptop],
    status: "active",
    tags: ["usb","c","hub"],
    createdAt: "2026-07-06T14:11:45.334Z",
    views: 265,
    saves: 34,
    offerCount: 6,
  },
  {
    id: "item-gen-111",
    sellerId: "seller-jordan",
    sellerName: "Jordan",
    sellerAvatar: student2,
    sellerCourse: "3rd year CSE",
    sellerRating: 4.8,
    title: "USB C Hub (4 ports)",
    description: "Has HDMI.",
    category: "Accessories" as any,
    condition: "Good" as any,
    price: 800,
    pickupArea: "Mech Block",
    images: [productLaptop],
    status: "active",
    tags: ["usb","c","hub"],
    createdAt: "2026-07-12T15:11:45.334Z",
    views: 59,
    saves: 5,
    offerCount: 1,
  },
  {
    id: "item-gen-112",
    sellerId: "seller-aisha",
    sellerName: "Aisha",
    sellerAvatar: student3,
    sellerCourse: "1st year ECE",
    sellerRating: 4.8,
    title: "Free Plastic Chair",
    description: "Moving out, take it.",
    category: "Free Items" as any,
    condition: "Good" as any,
    price: 0,
    pickupArea: "Hostel 1",
    images: [productLamp],
    status: "active",
    tags: ["free","plastic","chair"],
    createdAt: "2026-07-06T07:11:45.334Z",
    views: 36,
    saves: 5,
    offerCount: 0,
  },
  {
    id: "item-gen-113",
    sellerId: "seller-aisha",
    sellerName: "Aisha",
    sellerAvatar: student3,
    sellerCourse: "1st year ECE",
    sellerRating: 4.8,
    title: "Free 2nd Sem Notes",
    description: "Donating to juniors.",
    category: "Free Items" as any,
    condition: "Good" as any,
    price: 0,
    pickupArea: "Hostel 2",
    images: [productLamp],
    status: "active",
    tags: ["free","2nd","sem"],
    createdAt: "2026-06-30T00:11:45.334Z",
    views: 192,
    saves: 13,
    offerCount: 2,
  },
  {
    id: "item-gen-114",
    sellerId: "seller-nisha",
    sellerName: "Nisha",
    sellerAvatar: student3,
    sellerCourse: "Final year CSE",
    sellerRating: 4.9,
    title: "Free Old Fiction Books",
    description: "Dan Brown collection.",
    category: "Free Items" as any,
    condition: "Like new" as any,
    price: 0,
    pickupArea: "Gate 2",
    images: [productLamp],
    status: "active",
    tags: ["free","old","fiction"],
    createdAt: "2026-07-07T21:11:45.334Z",
    views: 218,
    saves: 34,
    offerCount: 0,
  },
  {
    id: "item-gen-115",
    sellerId: "seller-jordan",
    sellerName: "Jordan",
    sellerAvatar: student2,
    sellerCourse: "3rd year CSE",
    sellerRating: 4.8,
    title: "Free Chemistry Lab Coat",
    description: "Size M.",
    category: "Free Items" as any,
    condition: "Like new" as any,
    price: 0,
    pickupArea: "Hostel 2",
    images: [productLamp],
    status: "active",
    tags: ["free","chemistry","lab"],
    createdAt: "2026-07-12T18:11:45.334Z",
    views: 85,
    saves: 6,
    offerCount: 1,
  },
  {
    id: "item-gen-116",
    sellerId: "seller-rahul",
    sellerName: "Rahul",
    sellerAvatar: student2,
    sellerCourse: "4th year Mech",
    sellerRating: 4.6,
    title: "Free Bucket",
    description: "Clean.",
    category: "Free Items" as any,
    condition: "Used" as any,
    price: 0,
    pickupArea: "Girls Hostel Block B",
    images: [productLamp],
    status: "active",
    tags: ["free","bucket"],
    createdAt: "2026-06-30T11:11:45.334Z",
    views: 234,
    saves: 16,
    offerCount: 1,
  },
];
