/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TuitionRouteImport } from './routes/tuition'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoommatesRouteImport } from './routes/roommates'
import { Route as RidesRouteImport } from './routes/rides'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MarketplacePremiumRouteImport } from './routes/marketplace-premium'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LostFoundRouteImport } from './routes/lost-found'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DatingRouteImport } from './routes/dating'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingCampusSpacesRouteImport } from './routes/onboarding/campus-spaces'
import { Route as MarketplaceSettingsRouteImport } from './routes/marketplace_.settings'
import { Route as MarketplaceHelpRouteImport } from './routes/marketplace_.help'
import { Route as MarketplaceBackupRouteImport } from './routes/marketplace.backup'
import { Route as LostFoundSettingsRouteImport } from './routes/lost-found_.settings'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as MarketplaceSellerIdRouteImport } from './routes/marketplace_.seller.$id'
import { Route as MarketplaceProductIdRouteImport } from './routes/marketplace_.product.$id'
import { Route as MarketplaceChatIdRouteImport } from './routes/marketplace_.chat.$id'

const TuitionRoute = TuitionRouteImport.update({
  id: '/tuition',
  path: '/tuition',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoommatesRoute = RoommatesRouteImport.update({
  id: '/roommates',
  path: '/roommates',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRoute = RidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplacePremiumRoute = MarketplacePremiumRouteImport.update({
  id: '/marketplace-premium',
  path: '/marketplace-premium',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LostFoundRoute = LostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DatingRoute = DatingRouteImport.update({
  id: '/dating',
  path: '/dating',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCampusSpacesRoute = OnboardingCampusSpacesRouteImport.update({
  id: '/onboarding/campus-spaces',
  path: '/onboarding/campus-spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSettingsRoute = MarketplaceSettingsRouteImport.update({
  id: '/marketplace_/settings',
  path: '/marketplace/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceHelpRoute = MarketplaceHelpRouteImport.update({
  id: '/marketplace_/help',
  path: '/marketplace/help',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceBackupRoute = MarketplaceBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => MarketplaceRoute,
} as any)
const LostFoundSettingsRoute = LostFoundSettingsRouteImport.update({
  id: '/lost-found_/settings',
  path: '/lost-found/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const MarketplaceSellerIdRoute = MarketplaceSellerIdRouteImport.update({
  id: '/marketplace_/seller/$id',
  path: '/marketplace/seller/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceProductIdRoute = MarketplaceProductIdRouteImport.update({
  id: '/marketplace_/product/$id',
  path: '/marketplace/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceChatIdRoute = MarketplaceChatIdRouteImport.update({
  id: '/marketplace_/chat/$id',
  path: '/marketplace/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRoute
  '/dating': typeof DatingRoute
  '/events': typeof EventsRoute
  '/lost-found': typeof LostFoundRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/marketplace-premium': typeof MarketplacePremiumRoute
  '/notes': typeof NotesRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/rides': typeof RidesRoute
  '/roommates': typeof RoommatesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tuition': typeof TuitionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/lost-found/settings': typeof LostFoundSettingsRoute
  '/marketplace/backup': typeof MarketplaceBackupRoute
  '/marketplace/help': typeof MarketplaceHelpRoute
  '/marketplace/settings': typeof MarketplaceSettingsRoute
  '/onboarding/campus-spaces': typeof OnboardingCampusSpacesRoute
  '/marketplace/chat/$id': typeof MarketplaceChatIdRoute
  '/marketplace/product/$id': typeof MarketplaceProductIdRoute
  '/marketplace/seller/$id': typeof MarketplaceSellerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRoute
  '/dating': typeof DatingRoute
  '/events': typeof EventsRoute
  '/lost-found': typeof LostFoundRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/marketplace-premium': typeof MarketplacePremiumRoute
  '/notes': typeof NotesRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/rides': typeof RidesRoute
  '/roommates': typeof RoommatesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tuition': typeof TuitionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/lost-found/settings': typeof LostFoundSettingsRoute
  '/marketplace/backup': typeof MarketplaceBackupRoute
  '/marketplace/help': typeof MarketplaceHelpRoute
  '/marketplace/settings': typeof MarketplaceSettingsRoute
  '/onboarding/campus-spaces': typeof OnboardingCampusSpacesRoute
  '/marketplace/chat/$id': typeof MarketplaceChatIdRoute
  '/marketplace/product/$id': typeof MarketplaceProductIdRoute
  '/marketplace/seller/$id': typeof MarketplaceSellerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRoute
  '/dating': typeof DatingRoute
  '/events': typeof EventsRoute
  '/lost-found': typeof LostFoundRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/marketplace-premium': typeof MarketplacePremiumRoute
  '/notes': typeof NotesRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/rides': typeof RidesRoute
  '/roommates': typeof RoommatesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tuition': typeof TuitionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/lost-found_/settings': typeof LostFoundSettingsRoute
  '/marketplace/backup': typeof MarketplaceBackupRoute
  '/marketplace_/help': typeof MarketplaceHelpRoute
  '/marketplace_/settings': typeof MarketplaceSettingsRoute
  '/onboarding/campus-spaces': typeof OnboardingCampusSpacesRoute
  '/marketplace_/chat/$id': typeof MarketplaceChatIdRoute
  '/marketplace_/product/$id': typeof MarketplaceProductIdRoute
  '/marketplace_/seller/$id': typeof MarketplaceSellerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/complete-profile'
    | '/dashboard'
    | '/dating'
    | '/events'
    | '/lost-found'
    | '/marketplace'
    | '/marketplace-premium'
    | '/notes'
    | '/privacy'
    | '/projects'
    | '/rides'
    | '/roommates'
    | '/settings'
    | '/terms'
    | '/tuition'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/signup'
    | '/lost-found/settings'
    | '/marketplace/backup'
    | '/marketplace/help'
    | '/marketplace/settings'
    | '/onboarding/campus-spaces'
    | '/marketplace/chat/$id'
    | '/marketplace/product/$id'
    | '/marketplace/seller/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/complete-profile'
    | '/dashboard'
    | '/dating'
    | '/events'
    | '/lost-found'
    | '/marketplace'
    | '/marketplace-premium'
    | '/notes'
    | '/privacy'
    | '/projects'
    | '/rides'
    | '/roommates'
    | '/settings'
    | '/terms'
    | '/tuition'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/signup'
    | '/lost-found/settings'
    | '/marketplace/backup'
    | '/marketplace/help'
    | '/marketplace/settings'
    | '/onboarding/campus-spaces'
    | '/marketplace/chat/$id'
    | '/marketplace/product/$id'
    | '/marketplace/seller/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/complete-profile'
    | '/dashboard'
    | '/dating'
    | '/events'
    | '/lost-found'
    | '/marketplace'
    | '/marketplace-premium'
    | '/notes'
    | '/privacy'
    | '/projects'
    | '/rides'
    | '/roommates'
    | '/settings'
    | '/terms'
    | '/tuition'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/signup'
    | '/lost-found_/settings'
    | '/marketplace/backup'
    | '/marketplace_/help'
    | '/marketplace_/settings'
    | '/onboarding/campus-spaces'
    | '/marketplace_/chat/$id'
    | '/marketplace_/product/$id'
    | '/marketplace_/seller/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  DashboardRoute: typeof DashboardRoute
  DatingRoute: typeof DatingRoute
  EventsRoute: typeof EventsRoute
  LostFoundRoute: typeof LostFoundRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  MarketplacePremiumRoute: typeof MarketplacePremiumRoute
  NotesRoute: typeof NotesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRoute
  RidesRoute: typeof RidesRoute
  RoommatesRoute: typeof RoommatesRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  TuitionRoute: typeof TuitionRoute
  LostFoundSettingsRoute: typeof LostFoundSettingsRoute
  MarketplaceHelpRoute: typeof MarketplaceHelpRoute
  MarketplaceSettingsRoute: typeof MarketplaceSettingsRoute
  OnboardingCampusSpacesRoute: typeof OnboardingCampusSpacesRoute
  MarketplaceChatIdRoute: typeof MarketplaceChatIdRoute
  MarketplaceProductIdRoute: typeof MarketplaceProductIdRoute
  MarketplaceSellerIdRoute: typeof MarketplaceSellerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tuition': {
      id: '/tuition'
      path: '/tuition'
      fullPath: '/tuition'
      preLoaderRoute: typeof TuitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roommates': {
      id: '/roommates'
      path: '/roommates'
      fullPath: '/roommates'
      preLoaderRoute: typeof RoommatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides': {
      id: '/rides'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof RidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-premium': {
      id: '/marketplace-premium'
      path: '/marketplace-premium'
      fullPath: '/marketplace-premium'
      preLoaderRoute: typeof MarketplacePremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost-found': {
      id: '/lost-found'
      path: '/lost-found'
      fullPath: '/lost-found'
      preLoaderRoute: typeof LostFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dating': {
      id: '/dating'
      path: '/dating'
      fullPath: '/dating'
      preLoaderRoute: typeof DatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/campus-spaces': {
      id: '/onboarding/campus-spaces'
      path: '/onboarding/campus-spaces'
      fullPath: '/onboarding/campus-spaces'
      preLoaderRoute: typeof OnboardingCampusSpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace_/settings': {
      id: '/marketplace_/settings'
      path: '/marketplace/settings'
      fullPath: '/marketplace/settings'
      preLoaderRoute: typeof MarketplaceSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace_/help': {
      id: '/marketplace_/help'
      path: '/marketplace/help'
      fullPath: '/marketplace/help'
      preLoaderRoute: typeof MarketplaceHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/backup': {
      id: '/marketplace/backup'
      path: '/backup'
      fullPath: '/marketplace/backup'
      preLoaderRoute: typeof MarketplaceBackupRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/lost-found_/settings': {
      id: '/lost-found_/settings'
      path: '/lost-found/settings'
      fullPath: '/lost-found/settings'
      preLoaderRoute: typeof LostFoundSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/marketplace_/seller/$id': {
      id: '/marketplace_/seller/$id'
      path: '/marketplace/seller/$id'
      fullPath: '/marketplace/seller/$id'
      preLoaderRoute: typeof MarketplaceSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace_/product/$id': {
      id: '/marketplace_/product/$id'
      path: '/marketplace/product/$id'
      fullPath: '/marketplace/product/$id'
      preLoaderRoute: typeof MarketplaceProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace_/chat/$id': {
      id: '/marketplace_/chat/$id'
      path: '/marketplace/chat/$id'
      fullPath: '/marketplace/chat/$id'
      preLoaderRoute: typeof MarketplaceChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceBackupRoute: typeof MarketplaceBackupRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceBackupRoute: MarketplaceBackupRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  DashboardRoute: DashboardRoute,
  DatingRoute: DatingRoute,
  EventsRoute: EventsRoute,
  LostFoundRoute: LostFoundRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  MarketplacePremiumRoute: MarketplacePremiumRoute,
  NotesRoute: NotesRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRoute,
  RidesRoute: RidesRoute,
  RoommatesRoute: RoommatesRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  TuitionRoute: TuitionRoute,
  LostFoundSettingsRoute: LostFoundSettingsRoute,
  MarketplaceHelpRoute: MarketplaceHelpRoute,
  MarketplaceSettingsRoute: MarketplaceSettingsRoute,
  OnboardingCampusSpacesRoute: OnboardingCampusSpacesRoute,
  MarketplaceChatIdRoute: MarketplaceChatIdRoute,
  MarketplaceProductIdRoute: MarketplaceProductIdRoute,
  MarketplaceSellerIdRoute: MarketplaceSellerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
